import { getFeatureFlag } from './flags';

export const PUBLIC_FLAGS = {
  FEATURE_VENDOR_HANDOFF: getFeatureFlag("NEXT_PUBLIC_FEATURE_VENDOR_HANDOFF", false),
  FEATURE_VENDOR_VISITS: getFeatureFlag("NEXT_PUBLIC_FEATURE_VENDOR_VISITS", false),
  FEATURE_VENDOR_QUOTES_VERSIONS: getFeatureFlag("NEXT_PUBLIC_FEATURE_VENDOR_QUOTES_VERSIONS", false),
  FEATURE_VENDOR_DASHBOARD_V2: getFeatureFlag("NEXT_PUBLIC_FEATURE_VENDOR_DASHBOARD_V2", false),
};




