import { NextResponse } from 'next/server';

export async function GET() {
  try {
    // These are the real images that were generated and uploaded to Supabase
    // Based on the logs from earlier generation attempts
    const realImages = [
      {
        id: '8384a590-b909-474e-8c9f-49fb3e43bbdb',
        name: 'Real OpenAI Generated Image 1',
        path: 'project-assets/f02c45c6-4f55-44d5-8da8-1be72a2c0ca0/0a6841b6-584e-41a9-8247-bae9b423aaa2/generated/8384a590-b909-474e-8c9f-49fb3e43bbdb.png'
      },
      {
        id: '474f969f-0d32-4916-a349-2d3ebac30249', 
        name: 'Real OpenAI Generated Image 2',
        path: 'project-assets/f02c45c6-4f55-44d5-8da8-1be72a2c0ca0/0a6841b6-584e-41a9-8247-bae9b423aaa2/generated/474f969f-0d32-4916-a349-2d3ebac30249.png'
      }
    ];

    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
    const bucket = process.env.SB_BUCKET_NAME || "event-images";

    const imagesWithUrls = realImages.map(img => ({
      ...img,
      publicUrl: `${supabaseUrl}/storage/v1/object/public/${bucket}/${img.path}`
    }));

    // Return HTML page to display the images
    const html = `
<!DOCTYPE html>
<html>
<head>
    <title>Real OpenAI Generated Images</title>
    <style>
        body { font-family: Arial, sans-serif; padding: 20px; background: #f5f5f5; }
        .container { max-width: 1200px; margin: 0 auto; }
        .header { background: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        .image-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(400px, 1fr)); gap: 20px; }
        .image-card { background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        .image-card img { width: 100%; height: auto; border-radius: 4px; }
        .image-info { margin-top: 10px; }
        .back-link { display: inline-block; margin-bottom: 20px; color: #0066cc; text-decoration: none; }
        .back-link:hover { text-decoration: underline; }
    </style>
</head>
<body>
    <div class="container">
        <a href="/project/f02c45c6-4f55-44d5-8da8-1be72a2c0ca0" class="back-link">← Back to Project</a>
        
        <div class="header">
            <h1>Real OpenAI Generated Images</h1>
            <p>These are the actual images generated by OpenAI (2MB+ each) that were uploaded to Supabase storage.</p>
            <p><strong>Note:</strong> These images exist in storage but weren't saved to the database, so they don't appear in the Designer Board yet.</p>
        </div>

        <div class="image-grid">
            ${imagesWithUrls.map(img => `
                <div class="image-card">
                    <img src="${img.publicUrl}" alt="${img.name}" onerror="this.style.display='none'; this.nextElementSibling.style.display='block';">
                    <div style="display:none; padding: 20px; text-align: center; color: #666;">
                        Image not found or failed to load
                    </div>
                    <div class="image-info">
                        <h3>${img.name}</h3>
                        <p><strong>Path:</strong> ${img.path}</p>
                        <p><strong>ID:</strong> ${img.id}</p>
                        <a href="${img.publicUrl}" target="_blank">Open Full Size</a>
                    </div>
                </div>
            `).join('')}
        </div>
    </div>
</body>
</html>`;

    return new NextResponse(html, {
      headers: {
        'Content-Type': 'text/html',
      },
    });
  } catch (error: any) {
    console.error('Error generating image viewer:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

