import { NextRequest, NextResponse } from 'next/server';
import { PrismaClient } from '@prisma/client';
import { sendEmail, generateEventInviteEmail } from '../../../../../utils/email';

const prisma = new PrismaClient();

// POST /api/subevents/[id]/invite
export async function POST(req: NextRequest, { params }: { params: { id: string } }) {
  try {
    const { email, message } = await req.json();
    
    if (!email) {
      return NextResponse.json(
        { error: 'Email is required' },
        { status: 400 }
      );
    }

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      return NextResponse.json(
        { error: 'Invalid email format' },
        { status: 400 }
      );
    }

    // Get sub-event details
    const subEvent = await prisma.subEvent.findUnique({
      where: { id: params.id },
      include: {
        event: {
          select: {
            id: true,
            title: true
          }
        },
        createdBy: {
          select: {
            id: true,
            name: true,
            email: true
          }
        }
      }
    });

    if (!subEvent) {
      return NextResponse.json(
        { error: 'Sub-event not found' },
        { status: 404 }
      );
    }

    // Check if invite already exists
    const existingInvite = await prisma.subEventInvite.findFirst({
      where: {
        subEventId: params.id,
        email: email.toLowerCase()
      }
    });

    if (existingInvite) {
      return NextResponse.json(
        { error: 'Invite already sent to this email' },
        { status: 409 }
      );
    }

    // Create invite
    const invite = await prisma.subEventInvite.create({
      data: {
        subEventId: params.id,
        email: email.toLowerCase(),
        invitedBy: subEvent.createdBy.id,
        message: message || null,
        status: 'pending',
        inviteToken: undefined, // auto-generated by Prisma
        expiresAt: undefined,   // auto-generated by Prisma
      },
      include: {
        subEvent: {
          include: {
            event: {
              select: {
                title: true
              }
            }
          }
        },
        invitedByUser: {
          select: {
            name: true
          }
        }
      }
    });

    // Send email invite
    const emailData = generateEventInviteEmail(
      email,
      subEvent.event.title,
      subEvent.title,
      invite.inviteToken,
      subEvent.createdBy.name || 'Event Organizer'
    );

    const emailResult = await sendEmail(emailData);
    
    if (!emailResult.success) {
      // Delete the invite if email failed
      await prisma.subEventInvite.delete({
        where: { id: invite.id }
      });
      
      return NextResponse.json(
        { error: 'Failed to send invite email' },
        { status: 500 }
      );
    }

    return NextResponse.json({
      success: true,
      invite: {
        id: invite.id,
        email: invite.email,
        status: invite.status,
        createdAt: invite.createdAt,
        expiresAt: invite.expiresAt
      }
    });

  } catch (error) {
    console.error('Error sending invite:', error);
    return NextResponse.json(
      { error: 'Failed to send invite' },
      { status: 500 }
    );
  }
}

// GET /api/subevents/[id]/invite - List invites for a sub-event
export async function GET(req: NextRequest, { params }: { params: { id: string } }) {
  try {
    const invites = await prisma.subEventInvite.findMany({
      where: {
        subEventId: params.id
      },
      orderBy: { createdAt: 'desc' },
      include: {
        user: {
          select: {
            id: true,
            name: true,
            email: true,
            profileImage: true
          }
        },
        invitedByUser: {
          select: {
            id: true,
            name: true,
            email: true
          }
        }
      }
    });

    return NextResponse.json(invites);
  } catch (error) {
    console.error('Error fetching invites:', error);
    return NextResponse.json(
      { error: 'Failed to fetch invites' },
      { status: 500 }
    );
  }
} 